#!/usr/bin/env node
// This file is auto-generated by @lark-apaas/fullstack-cli

const { nodeFileTrace } = require('@vercel/nft');
const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.resolve(__dirname, '..');

// 加载提交的 .env，供读取构建期配置（如 MIAODA_RUNTIME_ENTRIES）。dotenv 不一定安装 → 静默降级。
try {
  require('dotenv').config({ path: path.join(ROOT_DIR, '.env') });
} catch {
  // dotenv 未安装：跳过；MIAODA_RUNTIME_ENTRIES 仍可来自真实环境变量
}
const DIST_DIR = path.join(ROOT_DIR, 'dist');
const DIST_SERVER_DIR = path.join(DIST_DIR, 'server');
const ROOT_PACKAGE_JSON = path.join(ROOT_DIR, 'package.json');
const ROOT_NODE_MODULES = path.join(ROOT_DIR, 'node_modules');
const OUT_NODE_MODULES = path.join(DIST_DIR, 'node_modules');
const OUT_PACKAGE_JSON = path.join(DIST_DIR, 'package.json');

// Server 入口文件
const SERVER_ENTRY = path.join(DIST_SERVER_DIR, 'main.js');

// nest sourceRoot（源码根，默认 server）：把 .env 里声明的源码路径映射到构建产物位置
let SOURCE_ROOT = 'server';
try {
  const nestCli = JSON.parse(fs.readFileSync(path.join(ROOT_DIR, 'nest-cli.json'), 'utf8'));
  if (nestCli.sourceRoot) SOURCE_ROOT = nestCli.sourceRoot;
} catch {
  // 读不到 nest-cli.json 则用默认 server
}
const SRC_TO_OUT_EXT = { '.mts': '.mjs', '.cts': '.cjs', '.ts': '.js' };

// 额外 trace 入口：经 new Function/动态 import 加载、nft 无法从 main.js 静态发现的 ESM runtime。
// 应用在提交的 .env 里用 MIAODA_RUNTIME_ENTRIES 声明【源码路径】（相对项目根，逗号分隔），例如：
//   MIAODA_RUNTIME_ENTRIES=server/modules/ethics/runtime/review-run.mjs,server/modules/ethics/runtime/parse-core.mjs
// 脚本按 nest sourceRoot 自动映射到 dist/server 下的构建产物（并重写 .mts→.mjs / .ts→.js）。
const RUNTIME_ENTRIES = (process.env.MIAODA_RUNTIME_ENTRIES || '')
  .split(',')
  .map((s) => s.trim())
  .filter(Boolean)
  .map((srcRel) => {
    const fromSrc = path.relative(SOURCE_ROOT, srcRel); // 去掉 sourceRoot 前缀
    const ext = path.extname(fromSrc);
    const outRel = SRC_TO_OUT_EXT[ext] ? fromSrc.slice(0, -ext.length) + SRC_TO_OUT_EXT[ext] : fromSrc;
    return path.join(DIST_SERVER_DIR, outRel);
  })
  .filter((p) => {
    if (fs.existsSync(p)) return true;
    console.warn(`⚠️  MIAODA_RUNTIME_ENTRIES 入口在构建产物中不存在，已忽略: ${path.relative(ROOT_DIR, p)}`);
    return false;
  });

// Node.js 内置模块列表
const BUILTIN_MODULES = new Set([
  'assert', 'buffer', 'child_process', 'cluster', 'crypto', 'dgram', 'dns',
  'events', 'fs', 'http', 'http2', 'https', 'net', 'os', 'path', 'stream',
  'string_decoder', 'timers', 'tls', 'url', 'util', 'v8', 'vm', 'zlib',
  'async_hooks', 'perf_hooks', 'worker_threads', 'inspector', 'trace_events'
]);

/**
 * 从完整路径中提取 npm 包名（优化版）
 */
const nodeModulesSep = 'node_modules' + path.sep;
function extractPackageName(filePath) {
  const idx = filePath.lastIndexOf(nodeModulesSep);
  if (idx === -1) return null;

  const afterNodeModules = filePath.slice(idx + nodeModulesSep.length);
  const slashIdx = afterNodeModules.indexOf(path.sep);

  // 处理 scoped package (@xxx/yyy)
  if (afterNodeModules[0] === '@') {
    const secondSlash = afterNodeModules.indexOf(path.sep, slashIdx + 1);
    return secondSlash === -1
      ? afterNodeModules
      : afterNodeModules.slice(0, secondSlash);
  }

  return slashIdx === -1 ? afterNodeModules : afterNodeModules.slice(0, slashIdx);
}

/**
 * 递归删除目录
 */
function removeDir(dir) {
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

/**
 * 递归复制目录（优化版：优先使用硬链接）
 */
function copyDir(src, dest, stats = { hardLinks: 0, copies: 0 }) {
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(dest, { recursive: true });
  }

  const entries = fs.readdirSync(src, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.isDirectory()) {
      copyDir(srcPath, destPath, stats);
    } else {
      try {
        // 优先使用硬链接（CI 环境中安全，速度快，节省空间）
        fs.linkSync(srcPath, destPath);
        stats.hardLinks++;
      } catch {
        // 硬链接失败时回退到复制（如跨文件系统）
        fs.copyFileSync(srcPath, destPath);
        stats.copies++;
      }
    }
  }

  return stats;
}

/**
 * 选择性复制包
 */
function copyPackagesSelectively(packages, rootNodeModules, outNodeModules) {
  const copiedCount = { success: 0, failed: 0 };
  const fileStats = { hardLinks: 0, copies: 0 };

  // 确保输出目录存在
  if (fs.existsSync(outNodeModules)) {
    removeDir(outNodeModules);
  }
  fs.mkdirSync(outNodeModules, { recursive: true });

  // 复制每个包
  for (const pkg of packages) {
    const srcPath = path.join(rootNodeModules, pkg);
    const destPath = path.join(outNodeModules, pkg);

    if (!fs.existsSync(srcPath)) {
      copiedCount.failed++;
      continue;
    }

    try {
      // 确保父目录存在（处理 scoped packages）
      const destDir = path.dirname(destPath);
      if (!fs.existsSync(destDir)) {
        fs.mkdirSync(destDir, { recursive: true });
      }

      // 复制包目录，收集统计信息
      copyDir(srcPath, destPath, fileStats);
      copiedCount.success++;
    } catch (err) {
      console.error(`   ⚠️  复制失败: ${pkg} - ${err.message}`);
      copiedCount.failed++;
    }
  }

  return { copiedCount, fileStats };
}

/**
 * 主函数：智能裁剪
 */
async function smartPrune() {
  console.log('🔍 开始智能依赖分析...\n');

  const totalStartTime = Date.now();

  // 1. 检查入口文件是否存在
  if (!fs.existsSync(SERVER_ENTRY)) {
    console.error(`❌ 入口文件不存在: ${SERVER_ENTRY}`);
    console.error('   请先运行 npm run build:server');
    process.exit(1);
  }

  console.log(`📂 分析入口文件: ${path.relative(ROOT_DIR, SERVER_ENTRY)}`);
  if (RUNTIME_ENTRIES.length) {
    console.log(`📎 额外 trace 入口 (${RUNTIME_ENTRIES.length}): ${RUNTIME_ENTRIES.map((p) => path.relative(DIST_SERVER_DIR, p)).join(', ')}`);
  }

  // 2. 使用 @vercel/nft 追踪依赖
  console.log('🔎 追踪实际依赖...');
  const analyzeStart = Date.now();

  const { fileList } = await nodeFileTrace([SERVER_ENTRY, ...RUNTIME_ENTRIES], {
    base: ROOT_DIR,
    processCwd: ROOT_DIR,
    ts: false, // 禁用 TS 解析
    conditions: ['node', 'production'], // 只解析 Node.js 生产环境的导出
    exportsOnly: true, // 只使用 package.json 的 exports 字段
    analysis: {
      emitGlobs: false, // 禁用 glob 分析
      computeFileReferences: false, // 禁用文件引用计算
      evaluatePureExpressions: false, // 禁用纯表达式求值
    },
  });

  const analyzeElapsed = Date.now() - analyzeStart;
  console.log(`   ✅ 分析完成，耗时: ${analyzeElapsed}ms\n`);

  // 3. 提取 npm 包名（优化：减少字符串操作）
  const requiredPackages = new Set();

  for (const file of fileList) {
    // 快速跳过非 node_modules 文件
    if (!file.includes('node_modules')) continue;

    const pkgName = extractPackageName(file);
    if (pkgName && !BUILTIN_MODULES.has(pkgName)) {
      requiredPackages.add(pkgName);
    }
  }

  console.log(`📦 静态分析需要 ${requiredPackages.size} 个 npm 包`);

  // 4. 从 nft 结果递归收集子依赖（处理动态 require 无法被静态分析追踪的问题）
  // 某些包（如 pdf-parse）使用 try-catch 动态加载依赖（如 @napi-rs/canvas），
  // @vercel/nft 无法追踪这类依赖，需要基于 package.json 声明补充
  // 策略：只对 nft 已追踪到的包递归，避免收集无关依赖
  const originalPackage = JSON.parse(fs.readFileSync(ROOT_PACKAGE_JSON, 'utf8'));

  let addedSubDeps = 0;
  const visited = new Set(); // 防止循环依赖导致无限循环
  const queue = [...requiredPackages]; // BFS 队列，从 nft 结果开始（更精准）

  while (queue.length > 0) {
    const depName = queue.shift();

    // 跳过已访问的包（防止循环依赖）
    if (visited.has(depName)) continue;
    visited.add(depName);

    const depPkgPath = path.join(ROOT_NODE_MODULES, depName, 'package.json');
    if (!fs.existsSync(depPkgPath)) continue;

    try {
      const depPkg = JSON.parse(fs.readFileSync(depPkgPath, 'utf8'));
      const subDeps = {
        ...depPkg.dependencies,
        ...depPkg.optionalDependencies,
      };

      for (const subDep of Object.keys(subDeps)) {
        // 检查包是否存在于 node_modules 中
        const subDepPath = path.join(ROOT_NODE_MODULES, subDep);
        if (!fs.existsSync(subDepPath)) continue;

        // 如果是新发现的包，添加到结果集并加入队列继续遍历
        if (!requiredPackages.has(subDep)) {
          requiredPackages.add(subDep);
          addedSubDeps++;
        }

        // 无论是否已在 requiredPackages 中，都需要继续遍历其子依赖
        if (!visited.has(subDep)) {
          queue.push(subDep);
        }
      }
    } catch {
      // 忽略解析错误
    }
  }

  if (addedSubDeps > 0) {
    console.log(`📦 递归补充动态依赖，新增 ${addedSubDeps} 个包`);
  }

  // 5. 处理 actionPlugins（动态加载的插件，无法被静态分析追踪）
  const actionPlugins = originalPackage.actionPlugins || {};
  const actionPluginNames = Object.keys(actionPlugins);

  if (actionPluginNames.length > 0) {
    console.log(`🔌 发现 ${actionPluginNames.length} 个 Action 插件，添加到依赖列表...`);

    for (const pluginName of actionPluginNames) {
      requiredPackages.add(pluginName);

      // 检查插件的 peerDependencies，也添加进去
      const pluginPkgPath = path.join(ROOT_NODE_MODULES, pluginName, 'package.json');
      if (fs.existsSync(pluginPkgPath)) {
        try {
          const pluginPkg = JSON.parse(fs.readFileSync(pluginPkgPath, 'utf8'));
          if (pluginPkg.peerDependencies) {
            for (const peerDep of Object.keys(pluginPkg.peerDependencies)) {
              requiredPackages.add(peerDep);
            }
          }
        } catch {
          // 忽略解析错误
        }
      }
    }

    console.log(`   ✅ 插件: ${actionPluginNames.join(', ')}`);
  }

  console.log(`📦 总共需要 ${requiredPackages.size} 个 npm 包\n`);

  // 6. 选择性复制包（只复制需要的）
  console.log('📋 选择性复制 node_modules（仅复制需要的包）...');
  const copyStart = Date.now();

  const sortedPackages = Array.from(requiredPackages).sort();
  const { copiedCount, fileStats } = copyPackagesSelectively(sortedPackages, ROOT_NODE_MODULES, OUT_NODE_MODULES);

  const copyElapsed = Date.now() - copyStart;
  console.log(`   ✅ 复制完成，耗时: ${copyElapsed}ms`);
  console.log(`   成功: ${copiedCount.success} 个包，失败: ${copiedCount.failed} 个`);
  console.log(`   硬链接: ${fileStats.hardLinks} 个文件，复制: ${fileStats.copies} 个文件\n`);

  // 7. 生成精简版 package.json
  // 优化：直接构建 dependencies，避免多次对象展开
  const prunedDependencies = {};
  const allDeps = originalPackage.dependencies || {};
  const allDevDeps = originalPackage.devDependencies || {};

  for (const pkg of requiredPackages) {
    // 优先从 dependencies/devDependencies 获取版本，其次从 actionPlugins 获取
    const version = allDeps[pkg] || allDevDeps[pkg] || actionPlugins[pkg];
    if (version) {
      prunedDependencies[pkg] = version;
    }
  }

  const prunedPackage = {
    name: originalPackage.name,
    version: originalPackage.version,
    private: true,
    dependencies: prunedDependencies,
    engines: originalPackage.engines
  };

  fs.writeFileSync(OUT_PACKAGE_JSON, JSON.stringify(prunedPackage, null, 2));

  const totalElapsed = Date.now() - totalStartTime;

  // 8. 输出统计信息
  console.log('='.repeat(60));
  console.log('📊 智能裁剪统计:');
  console.log('='.repeat(60));
  console.log(`  需要的包数量:   ${requiredPackages.size}`);
  if (actionPluginNames.length > 0) {
    console.log(`  Action 插件:    ${actionPluginNames.length} 个`);
  }
  console.log(`  成功复制:       ${copiedCount.success} 个包`);
  console.log(`  失败:           ${copiedCount.failed} 个包`);
  console.log(`  硬链接文件:     ${fileStats.hardLinks} 个`);
  console.log(`  复制文件:       ${fileStats.copies} 个`);
  console.log(`  分析耗时:       ${analyzeElapsed}ms`);
  console.log(`  复制耗时:       ${copyElapsed}ms`);
  console.log(`  总耗时:         ${totalElapsed}ms`);
  console.log('='.repeat(60) + '\n');

  console.log('✅ 智能裁剪完成！');
  console.log(`📍 精简的 package.json 已保存到: ${OUT_PACKAGE_JSON}\n`);
}

// 运行智能裁剪
smartPrune().catch(err => {
  console.error('❌ 智能裁剪失败:', err);
  process.exit(1);
});
