#!/usr/bin/env bash
# This file is auto-generated by @lark-apaas/fullstack-cli

# 生产环境下，启动服务
# 从 dist/ 根目录执行，确保 process.cwd() 与 dev 模式一致
# dev: cwd = 项目根, shared/ client/ 可达
# prod: cwd = dist/,  shared/ client/ 可达
NODE_ENV=production node server/main.js
